version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tutorial-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1msvy8rkbskhx"
s3_prefix = "tutorial-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
