AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  manoloui.com SAM template

Resources:
  VisitorCounterLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        VisitorCounterApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables: 
          TABLE_NAME : !Ref VisitorsTable
          CORS_URL: https://manoloui.com
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorsTable

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref ServerlessRestApi
          Stage: Prod
      Description: Usage plan for visitor counter api
      Quota:
        Limit: 100
        Period: DAY
      Throttle:
        BurstLimit: 100
        RateLimit: 20
      UsagePlanName: VisitorsApiUsagePlan

  VisitorsTable:
    Type: AWS::Serverless::SimpleTable

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"